<!-- client/src/components/drawers/CreateUpdateLandHolding.vue -->
<template>
	<TransitionRoot as="template" :show="isVisible">
		<Dialog class="relative z-10" @close="closeDrawer">
			<div class="fixed inset-0" />

			<div class="fixed inset-0 overflow-hidden">
				<div class="absolute inset-0 overflow-hidden">
					<div
						class="pointer-events-none fixed inset-y-0 right-0 flex max-w-full pl-10"
					>
						<TransitionChild
							as="template"
							enter="transform transition ease-in-out duration-500 sm:duration-700"
							enter-from="translate-x-full"
							enter-to="translate-x-0"
							leave="transform transition ease-in-out duration-500 sm:duration-700"
							leave-from="translate-x-0"
							leave-to="translate-x-full"
						>
							<DialogPanel class="pointer-events-auto w-screen max-w-md">
								<div
									class="flex h-full flex-col overflow-y-scroll bg-white py-6 shadow-xl"
								>
									<div class="px-4 sm:px-6">
										<div class="flex items-start justify-between">
											<DialogTitle
												class="text-base font-semibold leading-6 text-gray-900"
											>
												{{
													mode === "create"
														? "Create Land Holding"
														: "Update Land Holding"
												}}
											</DialogTitle>
											<div class="ml-3 flex h-7 items-center">
												<button
													type="button"
													class="relative rounded-md bg-white text-gray-400 hover:text-gray-500 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2"
													@click="closeDrawer"
												>
													<span class="absolute -inset-2.5" />
													<span class="sr-only">Close panel</span>
													<XMarkIcon class="h-6 w-6" aria-hidden="true" />
												</button>
											</div>
										</div>
									</div>

									<!-- Form content starts here -->
									<div class="relative mt-6 flex-1 px-4 sm:px-6">
										<form @submit.prevent="handleSubmit">
											<div class="space-y-12">
												<div class="border-b border-gray-200 pb-12">
													<h2
														class="text-base font-semibold leading-7 text-gray-900"
													>
														Land Holding Information
													</h2>
													<p class="mt-1 text-sm leading-6 text-gray-500">
														Fill in the details for the land holding.
													</p>

													<div
														class="mt-10 grid grid-cols-1 gap-x-6 gap-y-8 sm:grid-cols-6"
													>
														<!-- Name (Autogenerated) -->
														<div class="sm:col-span-4">
															<label
																for="name"
																class="block text-sm font-medium leading-6 text-gray-900"
															>
																Name (Autogenerated)
															</label>
															<div class="mt-2">
																<input
																	v-model="landHoldingData.name"
																	id="name"
																	name="name"
																	type="text"
																	class="block w-full border border-gray-300 rounded-md shadow-sm py-1.5 px-3 bg-gray-100 text-gray-600 sm:text-sm sm:leading-6"
																	readonly
																/>
															</div>
														</div>

														<!-- Land Holding Owner -->
														<div class="sm:col-span-4">
															<label
																for="owner"
																class="block text-sm font-medium leading-6 text-gray-900"
															>
																Land Holding Owner
															</label>
															<div class="mt-2">
																<select
																	v-model="landHoldingData.owner"
																	id="title-source"
																	class="block w-full rounded-md border-0 bg-gray-50 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 focus:ring-2 focus:ring-indigo-500 sm:text-sm sm:leading-6"
																>
																	<option
																		v-for="owner in owners"
																		:key="owner._id"
																		:value="owner._id"
																	>
																		{{ owner.name }}
																	</option>
																</select>
															</div>
														</div>

														<!-- Legal Entity -->
														<div class="sm:col-span-4">
															<label
																for="legal-entity"
																class="block text-sm font-medium leading-6 text-gray-900"
															>
																Legal Entity
															</label>
															<div class="mt-2">
																<input
																	v-model="landHoldingData.legal_entity"
																	id="legal-entity"
																	type="text"
																	class="block w-full rounded-md border-0 bg-gray-50 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 focus:ring-2 focus:ring-indigo-500 sm:text-sm sm:leading-6"
																	required
																/>
															</div>
														</div>

														<!-- Net Mineral Acres -->
														<div class="sm:col-span-4">
															<label
																for="net-mineral-acres"
																class="block text-sm font-medium leading-6 text-gray-900"
															>
																Net Mineral Acres
															</label>
															<div class="mt-2">
																<input
																	v-model="landHoldingData.net_mineral_acres"
																	id="net-mineral-acres"
																	type="number"
																	class="block w-full rounded-md border-0 bg-gray-50 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 focus:ring-2 focus:ring-indigo-500 sm:text-sm sm:leading-6"
																	required
																/>
															</div>
														</div>

														<!-- Mineral Owner Royalty (%) -->
														<div class="sm:col-span-4">
															<label
																for="mineral-owner-royalty"
																class="block text-sm font-medium leading-6 text-gray-900"
															>
																Mineral Owner Royalty (%)
															</label>
															<div class="mt-2">
																<input
																	v-model="
																		landHoldingData.mineral_owner_royalty
																	"
																	id="mineral-owner-royalty"
																	type="number"
																	step="0.01"
																	min="0"
																	max="100"
																	class="block w-full rounded-md border-0 bg-gray-50 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 focus:ring-2 focus:ring-indigo-500 sm:text-sm sm:leading-6"
																	required
																/>
															</div>
														</div>

														<!-- Section Name (Autogenerated from Section, Township, Range) -->
														<div class="sm:col-span-4">
															<label
																for="section-name"
																class="block text-sm font-medium leading-6 text-gray-900"
															>
																Section Name (Autogenerated)
															</label>
															<div class="mt-2">
																<input
																	v-model="landHoldingData.section_name"
																	id="section-name"
																	type="text"
																	class="block w-full rounded-md border-0 bg-gray-50 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 focus:ring-2 focus:ring-indigo-500 sm:text-sm sm:leading-6"
																	readonly
																/>
															</div>
														</div>

														<!-- Section (3 characters) -->
														<div class="sm:col-span-2">
															<label
																for="section"
																class="block text-sm font-medium leading-6 text-gray-900"
															>
																Section (3 digits)
															</label>
															<div class="mt-2">
																<input
																	v-model="landHoldingData.section"
																	id="section"
																	type="text"
																	maxlength="3"
																	class="block w-full rounded-md border-0 bg-gray-50 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 focus:ring-2 focus:ring-indigo-500 sm:text-sm sm:leading-6"
																	required
																/>
															</div>
														</div>

														<!-- Township (4 characters) -->
														<div class="sm:col-span-2">
															<label
																for="township"
																class="block text-sm font-medium leading-6 text-gray-900"
															>
																Township (Format: 123N or 456S)
															</label>
															<div class="mt-2">
																<input
																	v-model="landHoldingData.township"
																	id="township"
																	type="text"
																	maxlength="4"
																	pattern="[0-9]{3}[NS]"
																	class="block w-full rounded-md border-0 bg-gray-50 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 focus:ring-2 focus:ring-indigo-500 sm:text-sm sm:leading-6"
																	required
																/>
															</div>
														</div>

														<!-- Range (4 characters) -->
														<div class="sm:col-span-2">
															<label
																for="range"
																class="block text-sm font-medium leading-6 text-gray-900"
															>
																Range (Format: 123E or 456W)
															</label>
															<div class="mt-2">
																<input
																	v-model="landHoldingData.range"
																	id="range"
																	type="text"
																	maxlength="4"
																	pattern="[0-9]{3}[EW]"
																	class="block w-full rounded-md border-0 bg-gray-50 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 focus:ring-2 focus:ring-indigo-500 sm:text-sm sm:leading-6"
																	required
																/>
															</div>
														</div>

														<!-- Title Source -->
														<div class="sm:col-span-4">
															<label
																for="title-source"
																class="block text-sm font-medium leading-6 text-gray-900"
															>
																Title Source
															</label>
															<div class="mt-2">
																<select
																	v-model="landHoldingData.title_source"
																	id="title-source"
																	class="block w-full rounded-md border-0 bg-gray-50 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 focus:ring-2 focus:ring-indigo-500 sm:text-sm sm:leading-6"
																>
																	<option value="Class A">Class A</option>
																	<option value="Class B">Class B</option>
																	<option value="Class C">Class C</option>
																	<option value="Class D">Class D</option>
																</select>
															</div>
														</div>
													</div>
												</div>
											</div>

											<!-- Buttons -->
											<div class="mt-6 flex items-center justify-end gap-x-6">
												<button
													type="button"
													class="text-sm font-semibold leading-6 text-gray-900"
													@click="closeDrawer"
												>
													Cancel
												</button>
												<button
													type="submit"
													class="rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600"
												>
													{{
														mode === "create"
															? "Create Land Holding"
															: "Update Land Holding"
													}}
												</button>
											</div>
										</form>
									</div>
								</div>
							</DialogPanel>
						</TransitionChild>
					</div>
				</div>
			</div>
		</Dialog>
	</TransitionRoot>
</template>

<script setup>
import {
	Dialog,
	DialogPanel,
	DialogTitle,
	TransitionChild,
	TransitionRoot,
} from "@headlessui/vue";
import { XMarkIcon } from "@heroicons/vue/24/outline";
import { reactive, ref, watch } from "vue";
import { useOwnerStore } from "../../stores/useOwnerStore";
import { useLandHoldingStore } from "../../stores/useLandHoldingStore";

const isUpdateMode = ref(false);
const errorMessage = ref("");
// Initialize store
const landHoldingStore = useLandHoldingStore();

// // Local state to control drawer visibility
// const isVisible = ref(false);

// Props for mode and selected owner
const props = defineProps({
	isVisible: Boolean,
	mode: String, // 'create' or 'update'
	owner: Object, // Owner object
	owners: Array, // List of owners
	landholding: Object, // Land holding object
});

// Reactive state for the land holding data
const landHoldingData = reactive({
	name: "",
	legal_entity: props.landholding?.legal_entity || "",
	net_mineral_acres: props.landholding?.net_mineral_acres || 0,
	mineral_owner_royalty: props.landholding?.mineral_owner_royalty || 0,
	section: props.landholding?.section || "",
	township: props.landholding?.township || "",
	range: props.landholding?.range || "",
	section_name: "",
	title_source: props.landholding?.title_source || "Class A",
});

// Watch for changes in the selected land holding and update landHoldingData accordingly
watch(
	() => props.landholding,
	(newLandHolding) => {
		if (newLandHolding && props.mode === "update") {
			Object.assign(landHoldingData, newLandHolding);
		}
	},
	{ immediate: true } // Pre-fill immediately if data is available
);

// Watch for changes in section, township, and range to auto-generate the section name and name
watch(
	() => [
		landHoldingData.legal_entity,
		landHoldingData.section,
		landHoldingData.township,
		landHoldingData.range,
	],
	([legal_entity, section, township, range]) => {
		landHoldingData.section_name = `${section}-${township}-${range}`;
		landHoldingData.name = `${landHoldingData.section_name} (${legal_entity})`;
	}
);

// Emits the close event
const emit = defineEmits(["close"]);

// Function to close the drawer
function closeDrawer() {
	emit("close");
}

// Handle form submit
async function handleSubmit() {
	if (props.mode === "create") {
		console.log("Creating land holding...");
		await handleCreateLandHolding();
	} else {
		console.log("Updating land holding...");
		await handleUpdateLandHolding();
	}
	closeDrawer();
}

// Function to handle Create Land Holding form submission
async function handleCreateLandHolding() {
	try {
		// Ensure land holding is associated with the ownerId
		landHoldingData.owner = props.owner._id;

		await landHoldingStore.createLandHolding(landHoldingData);
		console.log("Land Holding created successfully!: ", landHoldingData);
		console.log("Land Holding data owner: ", landHoldingData.owner);

		errorMessage.value = ""; // Reset error message
		// await landHoldingStore.getLandHoldings(props.owner._id);
		await landHoldingStore.getLandHoldings(props.owner._id); // Refresh the land holding list
	} catch (error) {
		console.error("Error creating land holding:" + error.message);
		errorMessage.value = "Failed to create land holding. Please try again.";
	}
}

// Function to handle Update Land Holding form submission
async function handleUpdateLandHolding() {
	// Ensure land holding is associated with the ownerId
	landHoldingData.owner = props.owner._id;

	if (!landHoldingData._id) {
		console.error("No land holding ID found for update");
		errorMessage.value = "No land holding ID found for update";
		return;
	}

	try {
		// Call the updateLandHolding method from the store
		await landHoldingStore.updateLandHolding(landHoldingData);
		console.log("Land Holding updated successfully!");
		await landHoldingStore.getLandHoldings(landHoldingData.owner); // Refresh the land holding list
	} catch (error) {
		console.error("Error updating land holding:" + error.message);
		errorMessage.value = "Failed to update land holding. Please try again.";
	}
}

const open = ref(true);
</script>
